### ISSUE TITLE
configparser crashes on ddcutil capabilities output

### ISSUE THREAD

**Issue by danfos** [digitaltrails/vdu_controls#12]
I did install vducontrols on Tumbleweed and see it is crashing parsing the _ddcutil capabilities_ output for my monitor, see below for the details.

I had a look at the _ddcutil capabilities_ output and thought the problem was this piece of the output

```
   Feature: 70 (Video black level: Blue)
   Feature: 72 (Gamma)
      Specific presets of absolute adjustment supported (0xfb)
      Absolute tolerance: +/- 5% (=0x05)
      Native gamma: 2.20 (0x78)
      Specific presets:  1.80 (0x50), 2.00 (0x64), 2.20 (0x78), 2.40 (0x8c), 2.60 (0xa0)
   Feature: 86 (Display Scaling)
```

The third line does not have a ':' in it, so I tried with that line removed:

`!self.capabilities_text = re.sub('\n[^:\n]+\n', self.capabilities_text)`

but that did not resolve the problem, the error changed only into "....at position 1541" and it is not immediately clear to me why.

I know I can create a config file myself and will likely do that but it looks to me the parser could use a bit more robustness.

Error running with changes:

```
> /usr/bin/vdu_controls
INFO: checking for config file '~/.config/vdu_controls/vdu_controls.conf'
INFO: application style is breeze
INFO: checking Display 1
   I2C bus:             /dev/i2c-4
   Monitor:             PHL:Philips 272C4:AU41322000155
INFO: checking for config file '~/.config/vdu_controls/Philips_272C4_AU41322000155.conf'
INFO: checking for config file '~/.config/vdu_controls/Philips_272C4.conf'
ERROR:
 Traceback (most recent call last):
  File "/usr/bin/vdu_controls", line 2413, in <module>
    main()
  File "/usr/bin/vdu_controls", line 2251, in main
    main_window = MainWindow(main_config, app)
  File "/usr/bin/vdu_controls", line 2159, in __init__
    self.main_control_panel = VduControlsMainPanel(main_config, detect_vdu_hook, app_context_menu)
  File "/usr/bin/vdu_controls", line 1616, in __init__
    controller = VduController(vdu_id, vdu_model_name, vdu_serial, manufacturer, default_config, self.ddcutil)
  File "/usr/bin/vdu_controls", line 979, in __init__
    self.config.set_capabilities_alt_text(self.capabilities_text)
  File "/usr/bin/vdu_controls", line 774, in set_capabilities_alt_text
    self.ini_content['ddcutil-capabilities']['capabilities-override'] = alt_text
  File "/usr/lib64/python3.8/configparser.py", line 1259, in __setitem__
    return self._parser.set(self._name, key, value)
  File "/usr/lib64/python3.8/configparser.py", line 1201, in set
    super().set(section, option, value)
  File "/usr/lib64/python3.8/configparser.py", line 894, in set
    value = self._interpolation.before_set(self, section, option,
  File "/usr/lib64/python3.8/configparser.py", line 402, in before_set
    raise ValueError("invalid interpolation syntax in %r at "
ValueError: invalid interpolation syntax in 'Model: 272C4QPJK\nMCCS version: 2.2\nCommands:\n   Command: 01 (VCP Request)\n   Command: 02 (VCP Response)\n   Command: 03 (VCP Set)\n   Command: 07 (Timing Request)\n   Command: 0c (Save Settings)\n   Command: e3 (Capabilities Reply)\n   Command: f3 (Capabilities Request)\nVCP Features:\n   Feature: 02 (New control value)\n   Feature: 04 (Restore factory defaults)\n   Feature: 05 (Restore factory brightness/contrast defaults)\n   Feature: 08 (Restore color defaults)\n   Feature: 0B (Color temperature increment)\n   Feature: 0C (Color temperature request)\n   Feature: 10 (Brightness)\n   Feature: 12 (Contrast)\n   Feature: 14 (Select color preset)\n      Values:\n         01: sRGB\n         04: 5000 K\n         05: 6500 K\n         06: 7500 K\n         07: 8200 K\n         08: 9300 K\n         0a: 11500 K\n         0b: User 1\n   Feature: 16 (Video gain: Red)\n   Feature: 18 (Video gain: Green)\n   Feature: 1A (Video gain: Blue)\n   Feature: 52 (Active control)\n   Feature: 54 (Performance Preservation)\n      Values: 00 01 (interpretation unavailable)\n   Feature: 60 (Input Source)\n      Values:\n         00: Unrecognized value\n         03: DVI-1\n         11: HDMI-1\n         12: HDMI-2\n         0f: DisplayPort-1\n         21: Unrecognized value\n         22: Unrecognized value\n         23: Unrecognized value\n         2f: Unrecognized value\n   Feature: 62 (Audio speaker volume)\n   Feature: 6C (Video black level: Red)\n   Feature: 6E (Video black level: Green)\n   Feature: 70 (Video black level: Blue)\n   Feature: 72 (Gamma)\n      Specific presets of absolute adjustment supported (0xfb)\n      Absolute tolerance: +/- 5% (=0x05)\n      Native gamma: 2.20 (0x78)\n      Specific presets:  1.80 (0x50), 2.00 (0x64), 2.20 (0x78), 2.40 (0x8c), 2.60 (0xa0)\n   Feature: 86 (Display Scaling)\n      Values:\n         01: No scaling\n         02: Max image, no aspect ration distortion\n         08: Linear expansion (compression) on h and v axes\n   Feature: 8D (Audio mute/Screen blank)\n      Values: 01 02 (interpretation unavailable)\n   Feature: 95 (Window Position(TL_X))\n   Feature: 96 (Window Position(TL_Y))\n   Feature: 97 (Window Position(BR_X))\n   Feature: 98 (Window Position(BR_Y))\n   Feature: A4 (Window mask control)\n   Feature: A5 (Change the selected window)\n   Feature: AC (Horizontal frequency)\n   Feature: AE (Vertical frequency)\n   Feature: B6 (Display technology type)\n   Feature: C0 (Display usage time)\n   Feature: C6 (Application enable key)\n   Feature: C8 (Display controller type)\n   Feature: C9 (Display firmware level)\n   Feature: CA (OSD/Button Control)\n      Values:\n         01: OSD disabled, button events enabled\n         02: OSD enabled, button events enabled\n   Feature: CC (OSD Language)\n      Values:\n         02: English\n         03: French\n         04: German\n         05: Italian\n         08: Portuguese (Portugal)\n         09: Russian\n         0a: Spanish\n         0c: Turkish\n         0d: Chinese (simplified / Kantai)\n   Feature: D6 (Power mode)\n      Values:\n         01: DPM: On,  DPMS: Off\n         04: DPM: Off, DPMS: Off\n         05: Write only value to turn off display\n   Feature: DC (Display Mode)\n      Values:\n         00: Standard/Default mode\n         01: Productivity\n         02: Mixed\n         03: Movie\n         04: User defined\n         05: Games\n         08: Standard/Default mode with intermediate power consumption\n   Feature: DF (VCP Version)\n   Feature: E4 (manufacturer specific feature)\n      Values: 00 01 (interpretation unavailable)\n   Feature: E5 (manufacturer specific feature)\n      Values: 00 01 (interpretation unavailable)\n   Feature: E8 (manufacturer specific feature)\n      Values: 00 01 (interpretation unavailable)\n   Feature: E9 (manufacturer specific feature)\n      Values: 00 02 (interpretation unavailable)\n   Feature: EA (manufacturer specific feature)\n   Feature: EB (manufacturer specific feature)\n      Values: 00 01 02 03 (interpretation unavailable)\n   Feature: EC (manufacturer specific feature)\n      Values: 00 01 02 03 04 (interpretation unavailable)\n   Feature: F0 (manufacturer specific feature)\n      Values: 00 01 (interpretation unavailable)\n   Feature: F6 (manufacturer specific feature)\n      Values: 01 02 (interpretation unavailable)\n   Feature: F7 (manufacturer specific feature)\n      Values: 00 01 (interpretation unavailable)\n   Feature: F9 (manufacturer specific feature)\n      Values: 00 01 02 03 04 (interpretation unavailable)\n   Feature: FA (manufacturer specific feature)\n      Values: 00 01 02 (interpretation unavailable)\n   Feature: FB (manufacturer specific feature)\n   Feature: FC (manufacturer specific feature)\n   Feature: FD (manufacturer specific feature)\n   Feature: FE (manufacturer specific feature)\n      Values: 00 01 02 04 (interpretation unavailable)\n   Feature: FF (manufacturer specific feature)\n' at position 1604
```

**Comment by digitaltrails** [comment]
At a guess it may be that there is something that needs escaping so that configparser is happy with it (perhaps a ':' in an unexpected place).  The configparser package is standard python, so I can't change that.  But I can fix what vdu_controls is writing to the config file in the first place.  Something to look at tomorrow (it's 23:26 here in NZ).

It's starting to appear that when it comes to manufacturers implementations of DDC, expect the unexpected.  So you are correct that further measures around robustness might be required. 

Thanks for taking the time to investigate and provide some feedback.  Much appreciated.

**Comment by digitaltrails** [comment]
I copied your Feature 72 specification into one of my own monitor configuration files.  If I remove the percent (%) sign it parses OK.  So I need to do something to escape the percent signs in the monitor metadata.  

BTW, as defined in the metadata, feature 72 would be unusable by vdu_controls.  But gamma isn't something supported out of the box by vdu_controls, so that's not so much of a problem.

**Comment by danfos** [comment]
> If I remove the percent (%) sign it parses OK. So I need to do something to escape the percent signs in the monitor metadata - replace % with %% should do it.

Yes, that did the trick:

`!self.capabilities_text = re.sub(r'%', '%%', self.capabilities_text)`

I see the double %% is also written in the config file using --create-config-files

Indeed, no need for feature 72 (Gamma) control.

> It's starting to appear that when it comes to manufacturers implementations of DDC, expect the unexpected. So you are correct that further measures around robustness might be required.

I was surprised that the configparser could at all parse this type of ddcutil capabilities output, I though INI was sections with tag=value statements but reading [it's documentation](https://docs.python.org/3/library/configparser.html) I see `:` is indeed also supported as lines without `:` so only escaping the `%` sign likely is a pretty good update that will not leave to much monitors erroring out. 

Thanks!

**Comment by digitaltrails** [comment]
OK - I've tweaked a copy of lines to turn % into %% when setting the configparser value for the metadata, configparser automatically reverses this when getting the data back.  Hopefully that should do the trick.  

I've pushed the change though to github, please could you see if this version (1.5.6) works any better.

At some point I will have to look into any other special characters and what to do about them.

**Comment by digitaltrails** [comment]
> > If I remove the percent (%) sign it parses OK. So I need to do something to escape the percent signs in the monitor metadata - replace % with %% should do it.
> 
> Yes, that did the trick:
> 
> `!self.capabilities_text = re.sub(r'%', '%%', self.capabilities_text)`
> 
I had to change two places, the second is inside the editor for the metadata textfield - it directly updates the configparser as the user types.

**Comment by danfos** [comment]
Our messages crossed...

I tried 1.5.6 and can confirm that fixes the problem.

Thanks, issue closed.

**Comment by digitaltrails** [comment]
> Our messages crossed...
> 
> I tried 1.5.6 and can confirm that fixes the problem.
> 
> Thanks, issue closed.

Yes, I noticed.  Thanks for the feedback and for helping with the issue.

BTW, I have had occasion to use viking in the past and may do in the future. In the last few years I haven't been anywhere where I needed a GPS, but hopefully one day.

**Comment by danfos** [comment]
Yes, did contribute to viking in the past, but largely moved to [QMapShack](https://github.com/Maproom/qmapshack/wiki)/[Brouter](https://github.com/abrensch/brouter), especially the [integration of Brouter into QMapShack](https://github.com/Maproom/qmapshack/wiki/DocGisItemsRouting#brouter) with on the fly routing is great for planning trips.
