### ISSUE TITLE
Scaling issue on HiDPI with Wayland

### ISSUE THREAD

**Issue by taprobane99** [digitaltrails/vdu_controls#16]
on my 4K display with 200% scaling vdu appears double the size it should be in wayland. it is also blurry but i guess that is a global xwayland issue.

can the scaling be fixed?

**Comment by digitaltrails** [comment]
That's a new one on me, I have a 27" 4K monitor, but I don't scale, I just adjusted font and icon sizes.  However looking at [https://wiki.archlinux.org/title/HiDPI](https://wiki.archlinux.org/title/HiDPI), it looks like there are some possibilities.

Starting vdu_controls with the QT_FONT_DPI certainly alters the font size, for example: 

`QT_FONT_DPI=96 vdu_controls`

But starting it with QT_SCALE_FACTOR with fractional scaling on my KDE desktop just destroys the layout.

`QT_SCALE_FACTOR=0.5  vdu_controls`

But as my desktop isn't set to scale to 200%, maybe you results will differ.   

The arch wiki page describes solutions for both gnome and kde, depending on what you're using, perhaps see if some of those suggestions help.

Is this a problem just for vdu_controls, or do any other Qt or KDE applications also act strangely?   If it's just vdu_controls, perhaps I can setup a test user, uses the same desktop env as your, set their desktop to scale and see what happens (my normal desktop is KDE-plasma on openSUSE tumbleweed).

**Comment by digitaltrails** [comment]
There is also some info at [https://doc.qt.io/qt-5/highdpi.html](https://doc.qt.io/qt-5/highdpi.html).  It might be worth trying:

`QT_AUTO_SCREEN_SCALE_FACTOR=0 vdu_controls`

The same web page also states that fractional scale factors may cause problems, so that may explain scaling 0.5 doesn't work.

There are other suggestions on the same page.

**Comment by taprobane99** [comment]
QT_AUTO_SCREEN_SCALE_FACTOR=0 set the font size correctly, and now for some reason just vdu_controls gives the same font size as that flag.

The program is usable now. I am on KDE 5.24.3. Perhaps somehow the flag got saved by kde.

The other issue is that the whole UI is blurry, but this must be because your code runs under xwayland rather than native wayland.

**Comment by digitaltrails** [comment]
> QT_AUTO_SCREEN_SCALE_FACTOR=0 set the font size correctly, and now for some reason just vdu_controls gives the same font size as that flag.
> 
> The program is usable now. I am on KDE 5.24.3. Perhaps somehow the flag got saved by kde.
> 
> The other issue is that the whole UI is blurry, but this must be because your code runs under xwayland rather than native wayland.

As long as Qt is setup to run under wayland, then vdu_controls should also run under wayland, it's not an X specific application, and I've made sure the code is wayland compatible.  When I've previously run it under wayland, I just assumed it was running natively.  Apparently xyes can be used to find out: [https://wiki.archlinux.org/title/wayland#Detect_Xwayland_applications_visually](https://wiki.archlinux.org/title/wayland#Detect_Xwayland_applications_visually)

I'll do a test of my own and see what results.

**Comment by taprobane99** [comment]
ok, i think the problem was that I was running vdu as sudo from the terminal.
with correct permissions set up and running non-sudo from the app menu it indeed runs as native wayland.

so i guess close this issue

**Comment by digitaltrails** [comment]
OK - closed.
