### ISSUE TITLE
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 31: invalid start byte

### ISSUE THREAD

**Issue by laggykiller** [digitaltrails/vdu_controls#20]
I am using Arch Linux and installed via AUR. Launching vdu_controls cause this error message:

```
INFO: checking for config file '/home/username/.config/vdu_controls/vdu_controls.conf'
INFO: application style is fusion
INFO: checking Display 1
   I2C bus:  /dev/i2c-13
   Monitor:             GSM:IPS226       :SerialNumber
INFO: checking for config file '/home/username/.config/vdu_controls/IPS226_SerialNumber.conf'
INFO: checking for config file '/home/username/.config/vdu_controls/IPS226.conf'
ERROR:
 Traceback (most recent call last):
  File "/usr/bin/vdu_controls", line 2752, in <module>
    main()
  File "/usr/bin/vdu_controls", line 2590, in main
    main_window = MainWindow(main_config, app)
  File "/usr/bin/vdu_controls", line 2427, in __init__
    self.main_control_panel = VduControlsMainPanel(main_config, detect_vdu_hook, app_context_menu)
  File "/usr/bin/vdu_controls", line 1765, in __init__
    controller = VduController(vdu_id, vdu_model_name, vdu_serial, manufacturer, default_config,
  File "/usr/bin/vdu_controls", line 1058, in __init__
    self.capabilities_text = ddcutil.query_capabilities(vdu_id)
  File "/usr/bin/vdu_controls", line 615, in query_capabilities
    capability_text = result.stdout.decode('utf-8')
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xff in position 31: invalid start byte
```

I tried to debug by adding `print(result.stdout)` before line 615. This is what it prints out:

```
b"Unparsed capabilities string: O\xff\xff\x02\x01hX\xba\x1b\x01\xfd\x93\xb3\x83/7j`\x81\xcc\xc9\xe3\xe8C\x02[U\xff\xff\x02\x01hX\xba\x1b\x01\xfd\x93\xb3\x83/7j`\x81\xcc\xc9\xe3\xe8C\x02[{\xff\xff\x02\x01hX\xba\x1b\x01\xfd\x93\xb3\x83/7j`\x81\xcc\xc9\xe3\xe8C\x02[\x01\xff\xff\x02\x01hX\xba\x1b\x01\xfd\x93\xb3\x83/7j`\x81\xcc\xc9\xe3\xe8C\x02['\xff\xff\x02\x01hX\xba\x1b\x01\xfd\x93\xb3\x83/7j`\x81\xcc\xc9\xe3\xe8C\x02[\xcd\xff\xff\x02\x01hX\xba\x1b\x01\xfd\x93\xb3\x83/7j`\x81\xcc\xc9\xe3\xe8C\x02[\xd3\xff\xff\x02\x01hX\xba\x1b\x01\xfd\x93\xb3\x83/7j`\x81\xcc\xc9\xe3\xe8C\x02[\xf9\xff\xff\x02\x01hX\xba\x1b\x01\xfd\x93\xb3\x83/7j`\x81\xcc\xc9\xe3\xe8C\x02[\x9f\xff\xff\x02\x01hX\xba\x1b\x01\xfd\x93\xb3\x83/7j`\x81\xcc\xc9\xe3\xe8C\x02[\xa5\xff\xff\x02\nErrors parsing capabilities string:\n   Nothing follows segment name at offset 238\nModel: Not specified\nMCCS version: Not specified\nVCP Features:\n"
```

It seems like running `ddcutil --sleep-multiplier 0.5 detect --terse` is working, but `ddcutil --sleep-multiplier 0.5 --display 1 capabilities` cause error

I was able to adjust brightness by Twinkle Tray in Windows, which is also an application that make use of DDC.

I am reporting this to ddcutil repo (https://github.com/rockowitz/ddcutil/issues/259). In the meantime, is it possible to warn user about this while allowing the option to procede and try to adjust brightness anyway? Or even better, being able to parse the capabilities string?

**Comment by digitaltrails** [comment]
> In the meantime, is it possible to warn user about this while allowing the option to procede and try to adjust brightness anyway? Or even better, being able to parse the capabilities string?

Yes, there may be a way.  You could manually create one of the config files that vdu_controls is looking for, such as /home/username/.config/vdu_controls/IPS226_SerialNumber.conf - add the minimum necessary definitions and capabilities, something like the following may work:

`[vdu-controls-widgets]
brightness = yes
contrast = yes
enable-vcp-codes = 

[ddcutil-parameters]
sleep-multiplier = 0.5

[ddcutil-capabilities]
capabilities-override =  Model: blah
                MCCS version: 2.2
                Commands:
                   Command: 01 (VCP Request)
                   Command: 02 (VCP Response)
                   Command: 03 (VCP Set)
                   Command: 07 (Timing Request)
                   Command: 0c (Save Settings)
                   Command: f3 (Capabilities Request)
                VCP Features:
                   Feature: 10 (Brightness)
                   Feature: 12 (Contrast)

`
The trailing blank line seems to be important, otherwise the last config line isn't parsed (probably a bug on my part).

**Comment by digitaltrails** [comment]
I'm sorry I took a while to get around to addressing this issue - some real life stuff and PC failures/rebuilds got in the way.
