### ISSUE TITLE
Fedora tries to ask for the wrong package while installing via RPM

### ISSUE THREAD

**Issue by grohan47** [digitaltrails/vdu_controls#21]
Fedora fails installation beacuse it is unable to download the python38-qt5 package, even though it has been installed via the package python3-qt5.

**Comment by digitaltrails** [comment]
> Fedora fails installation beacuse it is unable to download the python38-qt5 package, even though it has been installed via the package python3-qt5.

**Is this the rpm from https://software.opensuse.org/package/vdu_controls?**  In the spec for that package I need to change the dependencies to user non-version specific references - so python3-qt instead of python38-qt.

In the meantime I presume installing ignoring dependencies might work.

**Comment by digitaltrails** [comment]
I have updated the spec file for [https://software.opensuse.org/package/vdu_controls](https://software.opensuse.org/package/vdu_controls) so that the dependencies are now python3 and python3-qt5.  So if you are using RPM's from software.opensuse.org, they may now install cleanly.
