### ISSUE TITLE
Do not exit if no controllable monitor is found

### ISSUE THREAD

**Issue by kupiqu** [digitaltrails/vdu_controls#27]
I configured VDU Controls to autostart (being hidden in the systray) because from time to time I plug my laptop to an external monitor. Then all I need to do when I need it is to access VDU Controls in the systray.

However, VDU Controls does not allow to start when no monitors are plugged, so autostart won't work unless I start my session with the external monitor, which is not always the case:

![image](https://user-images.githubusercontent.com/3875196/194350948-e4e839fc-dacb-439f-877b-773e9d7c3409.png)

Would it be possible to allow VDU Controls to remain open even if not monitor is present at startup? Thanks!

**Comment by digitaltrails** [comment]
Good idea.  I don't have a functioning laptop, so I had not anticipated this requirement. This doesn't sound too hard to implement.  

The likely behaviour would be that the main panel would be empty except for the bottom bar.  I think this should be the behaviour by default - if a user want's to exit, they can just do that manually.    I will add a "error if no monitors" setting to control/suppress the error dialog for those folk that routinely run with no monitors.

It would be nice to support some laptop displays.  I believe the standards there are quite lacking.  Perhaps some models could be supported by providing some dummy/virtual DDC support via a wrapper around ddcutil.  That way vdu_controls does not have to get more complicated.  (I have a very old 586 Toshiba laptop and I have a US$12 SSD that I have earmarked as a replacement for it's hard-drive, one day I will see what I can do with it.)

**Comment by digitaltrails** [comment]
The new default behaviour is just to display a message in the main display in place of the monitor controls without invoking the error popup:

![Screenshot_20221007_160740](https://user-images.githubusercontent.com/5510901/194459635-add229c6-d87a-44eb-88ab-e98ff0d5f8f8.png)

The error-popup only displays if warnings are enabled.  In either case, warnings/no-warnings, the code no longer exits.
