### ISSUE TITLE
Internationalisation

### ISSUE THREAD

**Issue by digitaltrails** [digitaltrails/vdu_controls#30]
Version 1.8.2, includes code for localised language translations.  While a localisation capability now exists, I lack any properly proofed translations.  **Please contact me If you'd be interested in a localised version and would like to assist by proofreading a language file** (I can generate a starter file by using  sites such as google translate).

Here is a screenshot of vdu_controls localised by using scripts to bulk update Qt .ts files from text generated by [deepl.com](https://deepl.com) and google-translate.

![Screenshot_20221113_da_DK](https://user-images.githubusercontent.com/5510901/201494452-57a377f0-c3f8-4d8b-9041-991f70ea28cb.png)

**Comment by andreondra** [comment]
Hello, I can help with translating to Czech language if you are interested.

**Comment by digitaltrails** [comment]
> Hello, I can help with translating to Czech language if you are interested.

Thanks.  It would be nice to have someone actually using the internationalisation.
I don't think anyone is using the translations. No one has commented on them. I can't believe that [deepl.com](https://www.deepl.com/translator) and Google Translate have produced perfect results.  Because I have no evidence they are being used, I was thinking of stopping any further work on keeping them up to date (but I would continue to support internationalisation in the code).

If you would personally like a Czech translation and would use it, I'm happy to work with you on this if you are going to use it.  I'm not so keen on creating/supporting a translation if it won't be used.

I can easily generate a starter file, either blank, or with translations automatically generated from [deepl.com](https://www.deepl.com/translator) or Google Translate.  

If you want to see what you'd be getting into, have a look at one of the .ts files in the translation folder.  There are 255 messages definitions.  Unfortunately, the python code I used to populate the files escaped the unicode, which I don't think is necessary. If you were to go ahead, I would look into eliminate the escaping to make the translations more readable.

If you're actually intending to use the translation and are still keen, let me know.

**Comment by digitaltrails** [comment]
> ... Unfortunately, the python code I used to populate the files escaped the unicode, which I don't think is necessary. If you were to go ahead, I would look into eliminate the escaping to make the translations more readable.

It was bugging me, so I altered all the .ts files and python code that initialises them to use unicode.  So they should be much easier to read.

**Comment by andreondra** [comment]
Well, I will use the translations and it looks it is not too much of a work. If you can generate the starter files, I will get into it. Just let me know when they are ready :).

**Comment by digitaltrails** [comment]
> Well, I will use the translations and it looks it is not too much of a work. If you can generate the starter files, I will get into it. Just let me know when they are ready :).

Thanks, this is great news :).

I created the necessary files and opened a new issue #64 covering the work and including details on how to test.  I'm not that familiar with using Linux distro's language features - my apologies if my notes are unclear or too excessive.

**Comment by digitaltrails** [comment]
Internationalisation efforts and updates to translations have been suspended.  They may be resumed if there appear to be any actual users.
