### ISSUE TITLE
Building with PEP 517 standards fails

### ISSUE THREAD

**Issue by yochananmarqos** [digitaltrails/vdu_controls#33]
Running `python -m build --wheel --no-isolation` has failed since 1.8.2. It was working previously.

```
* Getting build dependencies for wheel...
error: Multiple top-level packages discovered in a flat-layout: ['translations', 'ddcutil_simulator_data'].

To avoid accidental inclusion of unwanted files or directories,
setuptools will not proceed with this build.

If you are trying to create a single distribution with multiple packages
on purpose, you should not rely on automatic discovery.
Instead, consider the following options:

1. set up custom discovery (`find` directive with `include` or `exclude`)
2. use a `src-layout`
3. explicitly set `py_modules` or `packages` with a list of names

To find more information, look for "package discovery" on setuptools docs.

ERROR Backend subprocess exited when trying to invoke get_requires_for_build_wheel
```

**Comment by digitaltrails** [comment]
> Running `python -m build --wheel --no-isolation` has failed since 1.8.2. It was working previously.
> 
> ```
> * Getting build dependencies for wheel...
> error: Multiple top-level packages discovered in a flat-layout: ['translations', 'ddcutil_simulator_data'].

So it looks like the folder's 'translations', 'ddcutil_simulator_data' are causing it to throw a wobbly.  Translations is certainly new.  I don't know what python -m build --wheel --no-isolation does exactly, something to do with packaging python modules it seems.  I'll do some research.

**Comment by yochananmarqos** [comment]
> throw a wobbly

I don't hear much British slang in the U.S., so I hadn't heard that one before. I rather like it. :grin: 

>  I'll do some research.

Copy that. Take your time and thanks for all your work on this project.

**Comment by digitaltrails** [comment]
Yep, it was the sub-folders.  The build though they were packages.  I've amended setup.cfg to declare that there are no packages(just the script).  I deleted and released v1.8.3.

**Comment by yochananmarqos** [comment]
@digitaltrails You bumped the 1.8.3 release tag, but it's the same commit as earlier and does not contain 912f586. :wink:

**Comment by digitaltrails** [comment]
> @digitaltrails You bumped the 1.8.3 release tag, but it's the same commit as earlier and does not contain [912f586](https://github.com/digitaltrails/vdu_controls/commit/912f5864a7fe24664af4205a7313dc17047a3a46). wink

Oops.  Forgot to delete the original tag (at least that's what I think happened).  Seems right now.

**Comment by yochananmarqos** [comment]
Yes, it's good now. Th


> I don't know what python -m build --wheel --no-isolation does exactly

Now it does this: 

```
* Getting build dependencies for wheel...
running egg_info
creating vdu_controls_digitaltrails.egg-info
writing vdu_controls_digitaltrails.egg-info/PKG-INFO
writing dependency_links to vdu_controls_digitaltrails.egg-info/dependency_links.txt
writing top-level names to vdu_controls_digitaltrails.egg-info/top_level.txt
writing manifest file 'vdu_controls_digitaltrails.egg-info/SOURCES.txt'
reading manifest file 'vdu_controls_digitaltrails.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE.md'
writing manifest file 'vdu_controls_digitaltrails.egg-info/SOURCES.txt'
* Building wheel...
running bdist_wheel
running build
running build_scripts
creating build
creating build/scripts-3.10
copying and adjusting vdu_controls.py -> build/scripts-3.10
changing mode of build/scripts-3.10/vdu_controls.py from 644 to 755
installing to build/bdist.linux-x86_64/wheel
running install
running install_egg_info
running egg_info
writing vdu_controls_digitaltrails.egg-info/PKG-INFO
writing dependency_links to vdu_controls_digitaltrails.egg-info/dependency_links.txt
writing top-level names to vdu_controls_digitaltrails.egg-info/top_level.txt
reading manifest file 'vdu_controls_digitaltrails.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
adding license file 'LICENSE.md'
writing manifest file 'vdu_controls_digitaltrails.egg-info/SOURCES.txt'
Copying vdu_controls_digitaltrails.egg-info to build/bdist.linux-x86_64/wheel/vdu_controls_digitaltrails-1.8.3-py3.10.egg-info
running install_scripts
creating build/bdist.linux-x86_64/wheel/vdu_controls_digitaltrails-1.8.3.data
creating build/bdist.linux-x86_64/wheel/vdu_controls_digitaltrails-1.8.3.data/scripts
copying build/scripts-3.10/vdu_controls.py -> build/bdist.linux-x86_64/wheel/vdu_controls_digitaltrails-1.8.3.data/scripts
changing mode of build/bdist.linux-x86_64/wheel/vdu_controls_digitaltrails-1.8.3.data/scripts/vdu_controls.py to 755
creating build/bdist.linux-x86_64/wheel/vdu_controls_digitaltrails-1.8.3.dist-info/WHEEL
creating '/mnt/storage/AUR/vdu_controls/src/vdu_controls-1.8.3/dist/.tmp-o0l35nfi/vdu_controls_digitaltrails-1.8.3-py3-none-any.whl' and adding 'build/bdist.linux-x86_64/wheel' to it
adding 'vdu_controls_digitaltrails-1.8.3.data/scripts/vdu_controls.py'
adding 'vdu_controls_digitaltrails-1.8.3.dist-info/LICENSE.md'
adding 'vdu_controls_digitaltrails-1.8.3.dist-info/METADATA'
adding 'vdu_controls_digitaltrails-1.8.3.dist-info/WHEEL'
adding 'vdu_controls_digitaltrails-1.8.3.dist-info/top_level.txt'
adding 'vdu_controls_digitaltrails-1.8.3.dist-info/RECORD'
removing build/bdist.linux-x86_64/wheel
Successfully built vdu_controls_digitaltrails-1.8.3-py3-none-any.whl
```

Then it can be installed using `python -m installer --destdir="$pkgdir" dist/*.whl`. See [Arch package guidelines](https://wiki.archlinux.org/title/Python_package_guidelines#Standards_based_(PEP_517))

I forgot to mention I'm the [`vdu_controls`](https://aur.archlinux.org/packages/vdu_controls) AUR package maintainer. I still have to install some files manually due to upstream Setuptools changes. See the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vdu_controls).

**Comment by digitaltrails** [comment]
> Yes, it's good now. Th
> 
> > I don't know what python -m build --wheel --no-isolation does exactly
> 
> Now it does this:
> 
> ```
> ...
> ```
> 
> Then it can be installed using `python -m installer --destdir="$pkgdir" dist/*.whl`. See [Arch package guidelines](https://wiki.archlinux.org/title/Python_package_guidelines#Standards_based_(PEP_517))
> 

Yes, I installed build and wheel in order to test the fix.  So many build/install systems.   I side stepped the python packaging conventions by keeping all the source code into one file.

> I forgot to mention I'm the [`vdu_controls`](https://aur.archlinux.org/packages/vdu_controls) AUR package maintainer. I still have to install some files manually due to upstream Setuptools changes. See the [PKGBUILD](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=vdu_controls).

I had already noted that.  Thank you for your efforts.  I think having in in the AUR may have helped bring in more feedback.  I also use the AUR build of vdu_controls on Manjaro.

I originally included a PKGBUILD for use on the OpenSUSE build service - the build service can build for Arch.  But I let that fall to the wayside because I get unexpected dependency errors:

[https://build.opensuse.org/package/show/home:mchnz/vdu_controls](https://build.opensuse.org/package/show/home:mchnz/vdu_controls)

Not sure if it's me or the OBS system (it may be the the OBS arch is a server-install focused VM).  

If it would help, I'm happy to use your PKGBUILD.
