### ISSUE TITLE
Idea: alternative widget using multiple buttons instead of a drop-down

### ISSUE THREAD

**Issue by denilsonsa** [digitaltrails/vdu_controls#36]
I got this idea from [qddcswitch](https://codeberg.org/Okxa/qddcswitch), please take a look at the screenshots over there.

The idea is to have an alternative implementation of non-continuous values. Instead of a drop-down selection box (that requires two clicks, and some precision), we could have multiple buttons side-by-side (requiring just one click). So, instead of this:

    ┌──────────────────┐   ┌──────────────────┐
    │ VGA-1          ▼ │ → │ VGA-1          ▼ │
    └──────────────────┘   └┬────────────────┬┘
                            │VGA-1           │
                            │DVI-1           │
                            │HDMI-1          │
                            └────────────────┘

We could have this:

    ┌────────┬────────┬────────┐
    │ VGA-1  │ DVI-1  │ HDMI-1 │
    └────────┴────────┴────────┘

This of course doesn't make sense if the amount of options is too high.

**Comment by RokeJulianLockhart** [comment]
Why a horizontal row instead of a vertical row? After all, that would be extensible since everyone's used to sidebars with scrollbars.

**Comment by digitaltrails** [comment]
Closing as infeasible to design and maintain in the existing codebase.  Something to consider if there is ever a rewrite from scratch.
