### ISSUE TITLE
Changes to the sleep modifier aren't detected as changed

### ISSUE THREAD

**Issue by denilsonsa** [digitaltrails/vdu_controls#37]
How to reproduce:

1. vdu_controls version 1.8.3 on Manjaro Linux.
2. Open the settings dialog.
3. You can reproduce this either on the main vdu_controls tab, or in each of the displays tabs.
4. Edit the value of sleep modifier. Let's say, from `0.5` to `0.25`.
5. Click Save.

What happens:

![Screenshot of the error message](https://user-images.githubusercontent.com/121676/211758432-32996093-a5cf-4523-bc23-faf8e207cafb.png)

**Comment by digitaltrails** [comment]
I can't reproduce this.  

1. Open settings
2. On the vdu_controls tab, change sleep modifier from 0.5 to 0.51
3. Click **save all**
4. Answer yes when asked about saving vdu_controls.conf

I just tried 1.8.3 on Manjaro 22.0 (gnome) -  it worked OK.   Also on OpenSUSE Tumbleweed (my normal desktop).

Perhaps something else has to go wrong first.  Have you tried this on a newly started vdu_controls.  It's possible some combination of things have to go wrong to trigger it.

**Comment by denilsonsa** [comment]
Look:

https://user-images.githubusercontent.com/121676/211767942-1e8cfb17-3867-4073-ba84-15ac639e089e.mp4

(As bonus, you can see me trying to click using the Wacom pen, as I described in #38.)

**Comment by digitaltrails** [comment]
Yes, but I can't get it to behave that way.  Perhaps there is something wrong with the config file.  Perhaps attach them as requested elsewhere.

**Comment by denilsonsa** [comment]
In case it helps reproducing this issue: [my_vdu_conf.zip](https://github.com/digitaltrails/vdu_controls/files/10390888/my_vdu_conf.zip)

**Comment by digitaltrails** [comment]
Thanks,  I'll take a look.   

I just now followed all the steps in your video, including starting with no config files both on Tumbleweed and real machine running Manjaro 22.0.0.  I cannot reproduce the error.  Very puzzling.

One possibility is if there is a way to leave the input field without an event being raised, but I haven't found a way to do that.  If that were the case, tabbing back through the field or pressing enter when in the field might shake it loose.

My Manjoro is not fully uptodate, I guess there could be a problem with an underlying library version, I'm updating it now.

Maybe the specifics of the monitors or the local environment are having some weird side effect - doesn't seem likely.

Maybe I should create a brand new user and login to a fresh environment.

**Comment by digitaltrails** [comment]
Just to confirm, this is vdu_controls 1.83 from the AUR -

```
md5sum /usr/bin/vdu_controls
24afeac8e3bb7068b57eda659ce6fd4e  /usr/bin/vdu_controls
```

**Comment by digitaltrails** [comment]
If you feel like doing some debugging you could use an editor and uncomment the print statement inside class SettingsEditorFloatWidget, at around line 1879 of vdu_controls:

        1878 def editing_finished() -> None:
        1879    # print(section, option, text_input.text())
        1880    section_editor.ini_editable[section][option] = str(text_input.text())

That would tell us whether the editing_finished handler is being called.   You would need to run vdu_controls in a konsole to see the output.

**Comment by denilsonsa** [comment]
I've uncommented that line. Absolutely nothing gets printed. That line is not executed.

I've also uncommented a similar line inside `SettingsEditorCsvWidget`, and in that one I can see the debugging output being printed after I edit the vcp codes and move focus away.

Upon saving the file, I noticed the vcp codes got saved, but the sleep multiplier was not saved. (Which makes sense, since that event handler never got called.)

---

I got it! Finally!

[QDoubleValidator::validate](https://doc.qt.io/qt-6/qdoublevalidator.html#validate) “Returns `Acceptable` if the string input contains a double that is within the valid range **and is in the correct format**.” (Emphasis mine.) I remembered my locale is set as:

```
LANG=en_GB.UTF-8
LC_CTYPE="en_GB.UTF-8"
LC_NUMERIC=nl_NL.UTF-8
LC_TIME=en_GB.UTF-8
LC_COLLATE="en_GB.UTF-8"
LC_MONETARY=nl_NL.UTF-8
LC_MESSAGES="en_GB.UTF-8"
[…]
LC_ALL=
```

And thus Qt wants the floating point number to be formatted with a comma as the decimal separator. When I changed from `0.5` to `0,5`, then the event was emitted and that function was called. But I'm assuming the rest of the code won't like commas, so I'm not saving that.

**Comment by digitaltrails** [comment]
For settings text_inputs that are floats, I will localize the displayed text, and delocalize the stored text.

**Comment by digitaltrails** [comment]
I added code to localize/delocalize floats.  I also added code to make the text red if the value is invalid (it seems there is no standard way to highlight a field as being in error in Qt).  Red seems quite visible in both dark and light themes, hopefully no one defaults their text to red.

**Comment by denilsonsa** [comment]
Hmm… The style is inconsistent. The _enable-vcp-codes_ changes the border and the text to red, while the _sleep-multiplier_ only changes the text.

Also, unfortunately the code still doesn't work, because the code to change the style lives inside `editing_finished`, which [doesn't get called if the validation fails](https://doc.qt.io/qt-6/qlineedit.html#editingFinished):

> This signal is emitted when the Return or Enter key is pressed, or if the line edit loses focus and its contents have changed since the last time this signal was emitted.
>
> Note that if there is a [validator](https://doc.qt.io/qt-6/qlineedit.html#validator)() or [inputMask](https://doc.qt.io/qt-6/qlineedit.html#inputMask-prop)() set on the line edit and enter/return is pressed, the editingFinished() signal will only be emitted if the input follows the [inputMask](https://doc.qt.io/qt-6/qlineedit.html#inputMask-prop)() and the [validator](https://doc.qt.io/qt-6/qlineedit.html#validator)() returns [QValidator::Acceptable](https://doc.qt.io/qt-6/qvalidator.html#State-enum).

Take a look at how your `SettingsEditorCsvWidget` handles it. And maybe move that common logic to a parent class.

**Comment by digitaltrails** [comment]
I did not know I had validation on the CSV.  Clearly I'm a bit punch drunk.   I don't see a red border on enable-vcp-codes, I do see red text.

The suggestions I seen elsewhere pretty much say the floating point validator is a bit of a pain, and it's best to subclass it or write one's own.

**Comment by denilsonsa** [comment]
> I don't see a red border on enable-vcp-codes

Try moving the focus away. The focus border has priority.

**Comment by digitaltrails** [comment]
> > I don't see a red border on enable-vcp-codes
> 
> Try moving the focus away. The focus border has priority.

I see.  

It seems I'm using style sheet changes for invalid items in some of the other fields.  I can't believe I did that, it must be quite early code, or I was in a hurry.  Using style sheets in Qt looks very inviting, but it can break desktop theming (including run-time theme changes).  

I'm not that happy with text color changes either - it may conflict with a desktop themes   It will certainly trip up folk who have set the text to default to red, and they're probably the kind of people you don't want to get on the wrong side of ;)    

I will look into some standard way of reporting errors and put it in a baseclass.

I will look at reworking the validators too.

**Comment by digitaltrails** [comment]
Errors will definitely flagged in red letters now.   The input field may also be marked in read, but that still depends on how the user leaves the input field.
