### ISSUE TITLE
GY30/BH1750 + Arduino Lux metering potential options

### ISSUE THREAD

**Issue by digitaltrails** [digitaltrails/vdu_controls#45]
A simple light meter can be build using an Arduino and a GY30/BH1750 sensor. [Removed reference to dead link]

This raises some possibilities for vdu_controls to initiate transitions depending on metered light levels.

Today I built a meter using an Arduino Nano - image of wiring:
![20230304_171125b](https://user-images.githubusercontent.com/5510901/222875267-8e8bd45d-752e-49cc-b739-68dfaf1543b8.jpg)

A simple Sketch using [Christopher Laws' BH1750 library](https://github.com/claws/BH1750) can be uploaded to the Arduino to retrieve a feed of Lux values:

```
#include <BH1750.h>
#include <Wire.h>

BH1750 lightMeter;

void setup() {
…  // Serial.println(F("BH1750 Lux values stream..."));
}

void loop() {
  float lux = lightMeter.readLightLevel();
  Serial.println(lux);
  delay(1000);
}
```
The feed of Lux values can be read from the USB tty on a Linux host.  This feed can be used to trigger presets by issuing Linux signals (an existing capability of vdu_controls):
```
import os
import time

import serial
from serial import SerialException
import psutil


class Level:

    def __init__(self, min_level, max_level, signal) -> None:
        super().__init__()
        self.min = min_level
        self.max = max_level
        self.signal = signal


# (Min light level, max light level, UNIX signal number for Preset)
LEVELS = [Level(100, 200, 40), 
          Level(201, 300, 41),
          Level(300, 900, 42)]


def signal_vdu_controls(signal: int) -> bool:
    for proc in psutil.process_iter():
        if 'vdu_controls' in proc.name():
            pid = proc.pid
            os.kill(pid, signal)
            return True
    return False


try:
    current_level = None
    with serial.Serial('/dev/ttyUSB0') as gy30:
        while True:
            try:
                buffer = gy30.readline()
                value = float(buffer.decode('utf-8').replace("\r\n", ''))
                print(f"lux={value:6.2f}")
                for level in LEVELS:
                    if level != current_level:
                        if level.min <= value <= level.max:
                            print("signal")
                            if signal_vdu_controls(level.signal):
                                current_level = level
                            time.sleep(120)
            except ValueError as ve:
                print(ve, buffer)
except SerialException as se:
    print(se)
```
The above works and triggers presets according to the specified levels.

The issue is, how best to integrate this:

- Built into vdu_controls.
- A separate system tray utility for Lux that can be used by anything.
- Just trigger Presets.
- Directly drive changes in brightness/contrast (how?).
- Does a UI need to help with a response curve (how do our eyes respond to changes in Lux).

Parking all of the above, pending time to properly investigate it.

**Comment by digitaltrails** [comment]
OK, in case anyone is interested in this issue, I've added the following to vdu_controls...

![Screenshot_20230319_175353-1a](https://user-images.githubusercontent.com/5510901/226154539-b8b29673-aac1-4b17-80e4-1591619cc4bc.jpg)

**Comment by digitaltrails** [comment]
Integrating Presets to lux metering.

* On the chart - allow a preset to be assigned to the chart at a lux value:
  * Copy Preset's brightness (if any) to one or more {vdu, lux, brightness, preset} datums. 
  * Or perhaps update the presets brightness from the values on the chart?  Probably not.
  * What to do if a Preset lacks one or more brightness values - interpolate on the 
    existing chart perhaps?
  * Persist each {vdu, lux, brightness, preset-name} as a datum in the config file.
* In the background lux worker - if a datum has a Preset, trigger it when the datum's 
  lux triggers and we have stepped to the final brightness values. This will then restore
  the Preset's other (non-brightness) settings.
* Issues:
  * What if a preset is deleted? Remove datum, or remove preset from datum?
  * What if a preset is independently saved (in the Preset Dialog) and it's new 
    brightness values differ from those on the chart - warn/ask remove from datum?
    (Note: increase coupling, decrease cohesion, of Presets and Lux).

**Comment by digitaltrails** [comment]
OK, third approach to connecting presets to lux metering:

* On the chart:
  * Click along the bottom lux axis to add/remove a vertical lines representing a Preset for that lux value.
  * For Presets that have brightness values, this creates non-deletable points on the preset profile for each VDU.
  * The non-deletable points will be deleted if the Preset is removed from the axis.
  * Use little red circles as guidance as to where to click.

This seems to work quite well and I will proceed with completing/testing this approach.  Working code has been pushed to v1.10 - it appears to be quite stable, but might error on exception cases, such as if a participating preset is altered or deleted:

![image](https://user-images.githubusercontent.com/5510901/231056934-93909c32-5ca3-44e3-83d3-949258c510ca.png)

**Comment by digitaltrails** [comment]
Implemented in [version 1.10](https://github.com/digitaltrails/vdu_controls/releases/tag/v1.10.0)

**Comment by major-mayer** [comment]
Shouldn't the sketch code look like this (I took this from the BH1750 lib's documentation and combined it with your existing code)?
```c
#include <BH1750.h>
#include <Wire.h>

BH1750 lightMeter;

void setup() {
  Serial.begin(9600);

  // Initialize the I2C bus (BH1750 library doesn't do this automatically)
  // On esp8266 devices you can select SCL and SDA pins using Wire.begin(D4, D3);
  Wire.begin();

  lightMeter.begin();
  Serial.println(F("BH1750 Lux values stream..."));
}

void loop() {
  float lux = lightMeter.readLightLevel();
  Serial.println(lux);
  delay(1000);
}
```

In my case, i found it quite confusing that the setup part was not included in the example.
Or is this something that differs from device to device?

**Comment by digitaltrails** [comment]
> Shouldn't the sketch code look like this (I took this from the BH1750 lib's documentation and combined it with your existing code)?
> 
> ...
> 
> In my case, i found it quite confusing that the setup part was not included in the example. Or is this something that differs from device to device?

I have no idea why I removed the setup code from the example, perhaps I was worried people might clobber the wrong device or, as you suggest, was worried whether the settings may differ from device to device.  

I've added the setup code I'm actually using back into the example.

Thanks for pointing out the issue.

**Comment by major-mayer** [comment]
Great, glad that I could help 👍
