### ISSUE TITLE
Fails on first run due to missing config file

### ISSUE THREAD

**Issue by crashmatt** [digitaltrails/vdu_controls#6]
Checks for existing monitor config here:
https://github.com/digitaltrails/vdu_controls/blob/ea498d7c3144cd5fcef35018bf660446636811bb/vdu_controls.py#L929

When running first time it doesn't find a config so it doesn't set self,config:
https://github.com/digitaltrails/vdu_controls/blob/ea498d7c3144cd5fcef35018bf660446636811bb/vdu_controls.py#L938

Then this line throws an error 
https://github.com/digitaltrails/vdu_controls/blob/ea498d7c3144cd5fcef35018bf660446636811bb/vdu_controls.py#L943

which reports 

_Error: AttributeError: 'NoneType' object has no attribute 'restrict_to_actual_capabilities'
Is --sleep-multiplier set too low?_

Probably need to move line 943 below line 948 and make it conditional on the test for self.config is None

Can't debug further since I now get the _No controllable monitors found_ error

**Comment by digitaltrails** [comment]
> Checks for existing monitor config here:
> 
> https://github.com/digitaltrails/vdu_controls/blob/ea498d7c3144cd5fcef35018bf660446636811bb/vdu_controls.py#L929
> 
> When running first time it doesn't find a config so it doesn't set self,config:
> 
> https://github.com/digitaltrails/vdu_controls/blob/ea498d7c3144cd5fcef35018bf660446636811bb/vdu_controls.py#L938
> 
> Then this line throws an error
> 
> https://github.com/digitaltrails/vdu_controls/blob/ea498d7c3144cd5fcef35018bf660446636811bb/vdu_controls.py#L943
> 
> which reports
> 
> _Error: AttributeError: 'NoneType' object has no attribute 'restrict_to_actual_capabilities' Is --sleep-multiplier set too low?_
> 
> Probably need to move line 943 below line 948 and make it conditional on the test for self.config is None
> 
> Can't debug further since I now get the _No controllable monitors found_ error

I must have "improved" the code at some point and neglected to test this case.  I've checked in your suggested change and pushed it to github.  I'll make a formal release later today.   

Thanks for the detailed analysis, very much appreciated.

In respect to  _No controllable monitors found error_, perhaps start by seeing if ddcutil is working properly.

**Comment by digitaltrails** [comment]
> Can't debug further since I now get the _No controllable monitors found_ error

Interesting, when I run outside of pycharm I get the this error, but not when running inside it, and not if I restore my existing config files.  I'm investigating.

**Comment by digitaltrails** [comment]
> > Can't debug further since I now get the _No controllable monitors found_ error
> 
> Interesting, when I run outside of pycharm I get the this error, but not when running inside it, and not if I restore my existing config files. I'm investigating.

I've found that pycharm is passing a command line parameter **--show brightness**.  Passing one enabled control such as brightness will get you going.   

Obviously the absence of config files is causing more than one issue.  Which makes sense if I haven't tested that case.

I can only surmise there are no other users of this software.  No other reports have been made and the bug has probably been there way before the recent release.

**Comment by digitaltrails** [comment]
The v1.5.4 release addresses both of the described problems.  Fresh RPM's have also been build for [OpenSUSE](https://software.opensuse.org/package/vdu_controls)

**Comment by crashmatt** [comment]
--show brightness option fixed it.
I suggest you default this option to enabled.  It may be the one thing that everyone wants to work first time around.

Thanks for your attention.  I now have a way to nicely control monitor brightness without one of those hacked screen overlay apps.

**Comment by digitaltrails** [comment]
> --show brightness option fixed it. I suggest you default this option to enabled. It may be the one thing that everyone wants to work first time around.
> 
> Thanks for your attention. I now have a way to nicely control monitor brightness without one of those hacked screen overlay apps.

Thanks for the feedback.  Yes, perhaps it would be best to go with a simpler default, with all the controls defaulting to on the app is quite slow to start.

I got sick of fiddling with the manual controls, but I really did need an easy way to adjust the HDR for night and day.
