### ISSUE TITLE
Fail to set color preset above 9 - Hex format problem?

### ISSUE THREAD

**Issue by crashmatt** [digitaltrails/vdu_controls#7]
When setting the colour preset to 0x0b it fails.  I suspect it is using the text value.   ddcutil needs the value in explicit hex "0xXX".  I get this error when setting values above 9.

![Screenshot from 2021-11-09 09-38-42](https://user-images.githubusercontent.com/351261/140890972-8f464bfb-d78d-4e7e-bf03-cbc469cfefe0.png)

MCCS version: 2.1
Commands:
   Command: 01 (VCP Request)
   Command: 02 (VCP Response)
   Command: 03 (VCP Set)
   Command: 07 (Timing Request)
   Command: 0c (Save Settings)
   Command: e3 (Capabilities Reply)
   Command: f3 (Capabilities Request)
VCP Features:
   Feature: 02 (New control value)
   Feature: 04 (Restore factory defaults)
   Feature: 05 (Restore factory brightness/contrast defaults)
   Feature: 08 (Restore color defaults)
   Feature: 10 (Brightness)
   Feature: 12 (Contrast)
   Feature: 14 (Select color preset)
      Values:
         04: 5000 K
         05: 6500 K
         06: 7500 K
         08: 9300 K
         09: 10000 K
         0b: User 1
         0c: User 2

**Comment by digitaltrails** [comment]
If you pass the --debug option to cdu_controls, the commands issued to ddcutil will be written to stdout.  The command can then be tried on the command line to see what needs to be changed.

The presets on my monitor don't have a standard VCP code, so I haven't tested this case.

**Comment by crashmatt** [comment]
Been experimenting with cmd line ddcutil.  Have not yet worked out if it prefers values with 0xXX format or not.  

With the format values above 9 work but I get the following error on one monitor but not the other.
_Setting value failed for feature 14. rc=EIO(-5): Input/output error_

If I don't use the format then I get this feedback and vdu_controls shows an error:
_(ddc_write_read_with_retry     ) Display_Handle[i2c: fd=3, busno=8], ddc_write_read() succeeded after 1 sleep and retry for DDC Null Response_

Not sure if these are are caused by or additional to the hex format.

ddcutil says the following:

       feature-code

       A feature-code is specified by its 2 character hex  feature  number,  with  or  without  a
       leading "0x", e.g.  0x10, 10

       new-value

       A number in the range 0..255

Given that ddcutil capabilities reports hex values its not surprising that ddcutil setvcp is getting confused.

**Comment by digitaltrails** [comment]
VCP code 14 is a CNC (COMPLEX_NON_CONTINUOUS_TYPE), which for some reason needs to be passed on the command line with the x prefix (x00).  

The metadata available to vdu_controls doesn't allow it to correctly "guess" the type and it's being treated as SNC (SIMPLE_NON_CONTINUOUS_TYPE). 

At the point where vdu_controls is reading in the metadata it could query the current value of VCP code and it could then receive the correct type as part of the result.  However all the get_attributes would slow down startup quite a bit.  It may be smarter to allow the normal get_attribute calls that populate the controls to cache the type for future use - I'm going to look into that and see how messy it gets.
