### ISSUE TITLE
App exits when closing main window when running in system tray 

### ISSUE THREAD

**Issue by crashmatt** [digitaltrails/vdu_controls#8]
App closes when running from system tray instead of hiding the main window.

Simple fix is to override closeEvent in VduControlsMainWindow.
Pull request coming as soon as I can.

**Comment by crashmatt** [comment]
https://github.com/digitaltrails/vdu_controls/pull/9

**Comment by digitaltrails** [comment]
Interesting, I'm not seeing that behaviour on my KDE desktop, are you running something other than KDE?  

I do see one anomaly, vdu_controls isn't automatically restarted on login, where as my other Qt application [jouno](https://github.com/digitaltrails/jouno) is restarted.  Jouno does intercept closeEvent to save Qt state, but it doesn't prevent it from completing, so when not running under KDE, jouno might have the same this same issue you are seeing.

Thanks for the patch, I should have some time to look into folding it in later today.
