### ISSUE TITLE
[Bug] Error: ValueError: math domain error

### ISSUE THREAD

**Issue by Milor123** [digitaltrails/vdu_controls#83]
Hello brother, I'm here again.
I take this opportunity to tell you that I have been very happy with the implementation of the physical sensor + VDU, it works great.

Today at the end of the afternoon something curious happened to me, suddenly my VDU threw the following error (I will leave the log at the end).
It's a little strange, but I think that at the time it happened I had programmed some light mode change (in the presets), I'm not sure.
However, now that I tried to open my VDU again, I still get this error.

```
Details: Traceback (most recent call last):
  File "/home/noe/bin/vdu_controls", line 8451, in <module>
    main()
  File "/home/noe/bin/vdu_controls", line 8373, in main
    VduAppWindow(main_config, app, main_controller)  # may need to assign this to a variable to prevent garbage collection?
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noe/bin/vdu_controls", line 7840, in __init__
    self.main_controller.configure_application(self)
  File "/home/noe/bin/vdu_controls", line 7247, in configure_application
    self.main_window.create_main_control_panel()
  File "/home/noe/bin/vdu_controls", line 7954, in create_main_control_panel
    if lux_manual_input := self.main_controller.lux_auto_controller.create_manual_input_control():
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noe/bin/vdu_controls", line 6716, in create_manual_input_control
    self.lux_slider = LuxAmbientSlider()
                      ^^^^^^^^^^^^^^^^^^
  File "/home/noe/bin/vdu_controls", line 6987, in __init__
    self.set_current_value(round(LuxMeterManualDevice.get_stored_value()))  # trigger side-effects.
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/noe/bin/vdu_controls", line 7004, in set_current_value
    self.lux_slider.setValue(round(math.log10(value) * 1000))
                                   ^^^^^^^^^^^^^^^^^
ValueError: math domain error

```

what should i do for fix it?

**Comment by digitaltrails** [comment]
It appears that value was zero or negative. That's normally what would cause math.log10() to throw a *math domain error*.  I'll take a look at the code add a check for this.

My guess is the sensor returned a zero or a negative number and the UI tried to show it, so if that happens I should boost the value up to 1 so the slider won't error.

**Comment by digitaltrails** [comment]
I've checked in a fix.  The code immediately above was already checking for this, but then went on to use the unchecked original value - boom!

**Comment by Milor123** [comment]
> I've checked in a fix. The code immediately above was already checking for this, but then went on to use the unchecked original value - boom!

Thank you very much bro !!! I've pulled and now my vdu works again !!! Thankssss 😄 ❤️
