### ISSUE TITLE
[Meta] Fedora Installation Package

### ISSUE THREAD

**Issue by RokeJulianLockhart** [digitaltrails/vdu_controls#97]
#### The `readMe` is unclear regarding where to acquire packages for non-OSTW `.RPMs`: [^1]

https://github.com/digitaltrails/vdu_controls/blob/f509740f71226d037b7b4a4e436903141e90603b/README.md?plain=1#L201:~:text=**OpenSUSE**%20and%20**-,Fedora,-**%20RPMs%20available states:

> There are also **OpenSUSE** and **Fedora** RPMs available at: [https://software.opensuse.org/package/vdu_controls](https://software.opensuse.org/package/vdu_controls)

However, https://software.opensuse.org/package/vdu_controls, even with "Unsupported distributions" visible, does not explicitly provide an option for Fedora. Consequently, do you expect those on Fedora to utilize the RPM packaged for openSUSE Tumbleweed, or have I looked in the wrong place?

[^1]: https://github.com/digitaltrails/vdu_controls/issues/97#event-14858675928

**Comment by digitaltrails** [comment]
I think the links used to be less obscure, perhaps the OpenSUSE page has changed, or my recollection is incorrect.   Currently you would need to open the _Unsupported distributions_ section of the page, and then follow [home:mchnz](https://build.opensuse.org/package/show/home%3Amchnz/vdu_controls)

And when on that page, along the left side, click on [Fedora_37](https://build.opensuse.org/projects/home:mchnz/packages/vdu_controls/repositories/Fedora_37/binaries)

**These are totally unofficial, built by me binaries. Built in a VM on the OpenSUSE build service, and never actually run on Fedora (at least not recently).**

**Comment by RokeJulianLockhart** [comment]
> https://github.com/digitaltrails/vdu_controls/issues/97#issuecomment-2436246037

Thanks, @digitaltrails.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/digitaltrails/vdu_controls/issues/97#issuecomment-2436246037

Thanks, @digitaltrails. However, https://build.opensuse.org/projects/home:mchnz/packages/vdu_controls/repositories/Fedora_37/binaries/x86_64/vdu_controls-2.1.1-7.1.noarch.rpm is rather old - the current release version of Fedora is 40, not 37. Is that expected?

**Comment by digitaltrails** [comment]
I can only build what OBS supports. Given it's only a script, hopefully it might still work.  It might also be possible to build fresh from the source rpm.

Note, I can't provide ddcutil-service for Fedora. I can't figure out how to get it's dependencies in the VM that builds it.  But it may well compile on a real Fedora.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/digitaltrails/vdu_controls/issues/97#issuecomment-2436270349

@digitaltrails, the aforementioned package installed and runs. However, it certainly has issues - it initially wasn't able to locate the monitor configuration, and the brightness reverts to its previous state approximately 1s after applying it.

**Comment by digitaltrails** [comment]
Is it reverting the brightness, or is something outside of vdu_controls.  KDE6 thinks it's in charge of brightness.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/digitaltrails/vdu_controls/issues/97#issuecomment-2436286960

@digitaltrails, I don't know how to ascertain that, although I'd presumed the same. If there's a way for me to disable the plasmoid, I'll try. However, I don't see a way to do so.

**Comment by digitaltrails** [comment]
> 1. Upon initial invocation, it was unable to locate the configuration for my monitor(s):

If it then worked on another try, it's probably the ddcutil sleep multiplier being too optimistic.  That's not a bug, more of a tuning problem that each user has to solve.

**Comment by digitaltrails** [comment]
> > [#97 (comment)](https://github.com/digitaltrails/vdu_controls/issues/97#issuecomment-2436286960)
> 
> @digitaltrails, I don't know how to ascertain that, although I'd presumed the same. If there's a way for me to disable the plasmoid, I'll try. However, I don't see a way to do so. I'll try running it with `plasmashell` `kquitapp`'d.

If you set the brightness via ddcutil command line, and then it reverts, it's almost certainly KDE6.  See the top of the vdu_controls readme for a warning.  See 

https://discuss.kde.org/t/powerdevil-is-re-setting-my-display-brightness-after-the-display-wakes-up/23079

And similar discussions in various distro mailing lists.  What a mess.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/digitaltrails/vdu_controls/issues/97#issuecomment-2436292823

@digitaltrails, perhaps explicitly state that it can be expected? I think it's reasonable to assume that a user would consider a failure with a large stop symbol to *seem* like a bug.

**Comment by RokeJulianLockhart** [comment]
> If you set the brightness via ddcutil command line, and then it reverts, it's almost certainly KDE6.

Yeah, [`ddcutil setvcp 10 70`](https://wiki.archlinux.org/index.php?title=Backlight&oldid=818313#External_monitors:~:text=ddcutil%20setvcp%2010%2070) reverts too. Thanks for that.

**Comment by digitaltrails** [comment]
> If it's not been reported to `bugs.kde.org`, I'll try.

I think it has.  I think there might be a discussing going on internally with some arguing that KDE should be totally in charge of brightness, period.  But others are more sane.  They don't seem to have thought about users with carefully calibrated displays.  I can't quite understand how they thought they could always know the correct thing to do - I mean, I could at any second decide to adjust my monitor via it's own controls.

**Comment by digitaltrails** [comment]
> @digitaltrails, perhaps explicitly state that it can be expected? I think it's reasonable to assume that a user would consider a failure with a large stop symbol to _seem_ like a bug.

The default is to Retry, which is a big hint.  But I'll think about a wording change.  Note also, that ongoing ddcutil development is trying to remove the need to adjust the sleep interval, so it may not be as big a problem with newer releases (>=2.0).

**Comment by beedell-roke** [comment]
Another thing I've noticed (which I'd usually put in a separate issue, but this is easier) is that VDU Controls doesn't adhere to the `kcm_fonts` preferences:

1.	![`Screenshot_20241024_214923`](https://github.com/user-attachments/assets/6ebc133b-9ffe-4b34-81e9-5981c139b087)

1.	![`Screenshot_20241024_215012`](https://github.com/user-attachments/assets/345f08fe-a0c3-4469-84cf-f0a6e84275a0)

I realize that this is a Qt application (rather than one employing the KDE Frameworks) but it's a somewhat significant accessibility defect.

**Comment by digitaltrails** [comment]
> I realize that this is a Qt application (rather than one employing the KDE Frameworks) but it's a somewhat significant accessibility defect.

You could raise that as an issue.  Not sure how I would tackle it.  Does gnome have the same/similar requirements?  

I'm relying on Qt to do whatever it thinks is right, so I don't pick fonts, it picks them for me.

**Comment by RokeJulianLockhart** [comment]
> I'm relying on Qt to do whatever it thinks is right, so I don't pick fonts, it picks them for me (I think, not that I've looked at any code around that recently).

It's not a matter of font choice (though I saw that the package had sensibly included Noto as a mandatory fallback). Rather, the *sizes* shouldn't be hardcoded. Are they? I presume so.

**Comment by digitaltrails** [comment]
> It's not a matter of font choice (though I saw that the package had sensibly included Noto as a mandatory fallback). Rather, the _sizes_ shouldn't be hardcoded. Are they? I presume so.

Fonts are generally left to whatever Qt decides, for example `QLabel("Some text")` is left to do it's own thing.

Items that need to relate to the font-size are scaled proportionally to the Qt decided font size using a function that extracts the size by doing `QFontMetrics(QLabel("ABC").font()).height()`.

It might be possible to get Qt to behave better.  There are a variety of environment variables.  As usual, the arch wiki is a good place to start looking for info [https://wiki.archlinux.org/title/HiDPI#Qt_5](https://wiki.archlinux.org/title/HiDPI#Qt_5). The link is about HiDPI, but contains some general info. HiDPI adds another can of worms to what things will look like (and whether 1cm will measure 1cm on screen - it will if I have anything to do with it).

Whatever is done, it has to work well across all desktops (or be trivial to switch on/off).

You could raise an issue if you like.

**Comment by beedell-roke** [comment]
> You could raise an issue if you like.

Thanks, @digitaltrails. I'll open an issue with [`#issuecomment-2437004447`](https://github.com/digitaltrails/vdu_controls/issues/97#issuecomment-2437004447) quoted. I should probably close this one considering that [`#issue-2612445272`](https://github.com/digitaltrails/vdu_controls/issues/97#issue-2612445272) has been remediated by [`commit/60f3520c27b9f435b7c5a88fd279869d51fb11d8#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R202`](https://github.com/digitaltrails/vdu_controls/commit/60f3520c27b9f435b7c5a88fd279869d51fb11d8#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R202:~:text=some%20unoffical%20**Fedora**%20RPMs%20available%20at:%20%5Bbuild.opensuse.org%5D(https://build.opensuse.org/projects/home:mchnz/packages/vdu_controls/repositories/Fedora_37/binaries)).

**Comment by digitaltrails** [comment]
> > I'll open an issue with that quoted.
> 
> @digitaltrails, I _think_ I forgot to, so before I do, is it alright if I ask you to determine whether reporting all of the undermentioned would be worth your time? If I were tracking this myself, I'd report them separately, but I don't know how you tend to track issues.
> 
> 1. As aforementioned, [the information window's fonts don't adhere to the system font size](https://github.com/digitaltrails/vdu_controls/issues/97#issuecomment-2436316104).

I think that this is a separate issue worth raising as such.

> 2. The main window doesn't launch at its minimum vertical size, leaving an unnecessary space between controls:

This also.  Curious, probably something to do with me adding scroll regions.


> 3. The information window isn't resizeable, so it shan't render on smartphone displays (like KDE Plasma Mobile or Phosh).

I would raise this and the following under one issue - _support mobile/smartphone sized form-factor_ - not sure how mobile and external monitors goes together though.

> 4. Likewise, the configuration window's preference labels aren't visible in such a form factor:

**Comment by digitaltrails** [comment]
> 2 The main window doesn't launch at its minimum vertical size, leaving an unnecessary space between controls:

I've pushed a fix for that. 

Prior to this change, the the size of the main window was only being adjusted if it increased in size, but not if it decreased.  I was trying not to mess too much with the users decisions about window size, because these sizes are preserved at exit and restored at startup.  

Only the height will automatically adjust, the width will stay as it was last set.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/digitaltrails/vdu_controls/issues/97#issuecomment-2465958549

@digitaltrails, thank you. It was a rather perfectionist criticism. I dare say I'm rather glad you remediated it though, since I've also had this problem with PyQt applications (I'm definitely going to steal your solution).
